default: &default
  adapter : postgresql
  encoding: unicode
  timeout : 5000
  pool    : <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port    : <%= ENV['CUPCAKE_DATABASE_PORT'] %> 
  host    : <%= ENV['CUPCAKE_DATABASE_HOST'] %>
  username: <%= ENV['CUPCAKE_DATABASE_USERNAME'] %> 
  password: <%= ENV['CUPCAKE_DATABASE_PASSWORD'] %> 

development:
  database: <%= ENV['CUPCAKE_DATABASE_NAME'] %>
  <<      : *default

test:
  database: <%= ENV['CUPCAKE_DATABASE_NAME'] %>
  <<      : *default

production:
  database: <%= ENV['CUPCAKE_DATABASE_NAME'] %>
  <<      : *default

